### ISSUE TITLE
Possible Incompatibility with Minecolonies? Or Server?

### ISSUE THREAD

**Issue by Chassx2** [MartinTheDragon/Nuclear-Tech-Mod-Remake#20]
### Polaroidal interference

- [x] The Polaroid was not broken

### Issue description

Possible Incompatibility with Minecolonies?

`---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 9/27/22, 8:28 PM
Description: Exception in server tick loop

java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.1.80.jar%2317!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at at.martinthedragon.nucleartech.item.AssemblyTemplateItem.m_6787_(AssemblyTemplateItem.kt:31) ~[nucleartech-1.18.2-0.0.17.0.jar%23375!/:0.0.17.0] {re:classloading}
	at com.minecolonies.api.compatibility.CompatibilityManager.discoverAllItems(CompatibilityManager.java:603) ~[minecolonies-1.18.2-1.0.1050-ALPHA.jar%23341!/:1.18.2-1.0.1050-ALPHA] {re:classloading}
	at com.minecolonies.api.compatibility.CompatibilityManager.discover(CompatibilityManager.java:206) ~[minecolonies-1.18.2-1.0.1050-ALPHA.jar%23341!/:1.18.2-1.0.1050-ALPHA] {re:classloading}
	at com.minecolonies.coremod.event.DataPackSyncEventHandler$ServerEvents.loadRecipes(DataPackSyncEventHandler.java:51) ~[minecolonies-1.18.2-1.0.1050-ALPHA.jar%23341!/:1.18.2-1.0.1050-ALPHA] {re:classloading}
	at com.minecolonies.coremod.event.DataPackSyncEventHandler$ServerEvents.onServerStarted(DataPackSyncEventHandler.java:119) ~[minecolonies-1.18.2-1.0.1050-ALPHA.jar%23341!/:1.18.2-1.0.1050-ALPHA] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1594_ServerEvents_onServerStarted_ServerStartedEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:103) ~[forge-1.18.2-40.1.80-universal.jar%23531!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:662) ~[server-1.18.2-20220404.173914-srg.jar%23526!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fantasy.mixins.json:MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23526!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fantasy.mixins.json:MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

### Steps to reproduce

Load Server with latest version of the mod.

### Forge version

40.1.80

### Nuclear Tech version

0.0.17

### (Crash) Log

https://pastebin.com/00h2ryLy

**Comment by MartinTheDragon** [comment]
Minecolonies appears to be using a method called `Item#fillItemCategory`, which is alright I guess, because there's pretty much no other way to find out *all* the items that really exist, but this method usually gets only called client-side, since it's used to display items in the creative tabs (an "item category" being a tab). And so for the assembly template, it looks like this:
```kotlin
override fun fillItemCategory(tab: CreativeModeTab, items: NonNullList<ItemStack>) {
    val level = Minecraft.getInstance().level
    if (allowdedIn(tab) && level != null) {
        items.addAll(getAllTemplates(level.recipeManager))
    }
}
```
I basically need to get an instance of the recipe manager for displaying all the templates for all the recipes, and since it's usually client-side only, I'm getting away with retrieving it from the `Minecraft` class, which also only exists on the client...

Thanks for reporting!
