### ISSUE TITLE
rod control column & leaus fuel rod

### ISSUE THREAD

**Issue by ZifyyCZ** [MartinTheDragon/Nuclear-Tech-Mod-Remake#25]
### Issue description

```
java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class at.martinthedragon.nucleartech.item.RBMKRodItem (net.minecraft.world.item.AirItem is in module minecraft@1.18.2 of loader 'TRANSFORMER' @6a5e167a; at.martinthedragon.nucleartech.item.RBMKRodItem is in module wf@1.3.1-BETA of loader 'TRANSFORMER' @6a5e167a)
	at at.martinthedragon.nucleartech.item.RBMKRodItem$Companion.getEnrichment(RBMKRodItem.kt:185) ~[warfrontmod-1.3.1-BETA.jar%2358!/:1.3.1-BETA] {re:classloading}
	at at.martinthedragon.nucleartech.block.entity.rbmk.RBMKRodBlockEntity.getConsoleData(RBMKRodBlockEntity.kt:255) ~[warfrontmod-1.3.1-BETA.jar%2358!/:1.3.1-BETA] {re:classloading}
	at at.martinthedragon.nucleartech.block.entity.rbmk.RBMKConsoleBlockEntity.rescan(RBMKConsoleBlockEntity.kt:69) ~[warfrontmod-1.3.1-BETA.jar%2358!/:1.3.1-BETA] {re:classloading}
	at at.martinthedragon.nucleartech.block.entity.rbmk.RBMKConsoleBlockEntity.serverTick(RBMKConsoleBlockEntity.kt:50) ~[warfrontmod-1.3.1-BETA.jar%2358!/:1.3.1-BETA] {re:classloading}
	at at.martinthedragon.nucleartech.api.block.entities.TickingServerBlockEntityKt.createServerTicker$lambda$0(TickingServerBlockEntity.kt:25) ~[warfrontmod-1.3.1-BETA.jar%2358!/:1.3.1-BETA] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
```

### Steps to reproduce

1. Take Leaus fuel rod
2. Put it in a control rod column (this one)
![obrázek_2022-12-25_143036922](https://user-images.githubusercontent.com/71338678/209469887-479f4204-01c5-4244-810a-9f14d89de01c.png)
3. error gets thrown 

### Forge version

40.1.86

### Nuclear Tech version

Manually compiled

### (Crash) Log

https://pastebin.com/799Zgubt

**Comment by MartinTheDragon** [comment]
Hello!
I can't seem to reproduce your issue. Does it occur only sometimes or every time?  Did you test the mod all by itself too? It could be a mod incompatibility somehow, because it seems like your Warfront mod took over the classpath module of NTM, kinda strange...
If possible, send a world file together with a mod list where this crash happens.
Merry Christmas (if you celebrate)!

**Comment by MartinTheDragon** [comment]
In fact, I can't even get to the title screen with the Warfront mod, here's part of the crash:

```
java.lang.RuntimeException: [WF] Could not download dependencies!
	at net.zifyy.mods.warfront.client.gui.TitleScreen.checkForDepndencies(TitleScreen.java:117) ~[warfrontmod-1.3.0-BETA.jar%2354!/:1.3.0-BETA] {re:classloading}
	at net.zifyy.mods.warfront.client.gui.TitleScreen.m_7856_(TitleScreen.java:405) ~[warfrontmod-1.3.0-BETA.jar%2354!/:1.3.0-BETA] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:423) ~[client-1.18.2-20220404.173914-srg.jar%2355!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
```

**Comment by MartinTheDragon** [comment]
Also, on your CurseForge page it says that your mod includes simple voice chat. Unfortunately, that mod is licensed under "All right reserved" (which is the default): `Copyright (c) Max Henkel - All Rights Reserved`.
Hopefully "include" is related to that download error on the title screen, because if your mod jar includes simple voice chat in your mod jar, that's not only bad practice, that's a possible DMCA claim and the Warfront mod could be taken down (although I'm not even sure if "All rights reserved" technically allows you to play with the mod at all, but it definitely doesn't allow you to include it).

**Comment by ZifyyCZ** [comment]
Thanks for the info. I didn't even know I still had the Voicechat mod there. (As the Warfront mod is basically for an SMP - modpack with more mods needed, which will include the Voicechat mod too) Also I tried to do the same thing again and it works. Might've been issue of my own mod. Yet again, thanks!
